package appinicialprofe.basico;

/**
 * HACED UN PROGRAMA QUE JUEGUE COPN EL USUARIO
 * A ADIVINAR UN NÚMERO
 * 
 * EL PROGRAMA (LA MÁQUINA) PIENSA UN NÚMERO
 * ALEATORIO ENTRE 1 Y 100
 * 
 * Y LE DA 5 OPORTUNIDADES AL USUARIO PARA 
 * AVERIGUARLO
 * 
 * POR CADA INTENTO, EL PROGRAMA LE DA UNA PISTA
 * AL USUARIO. 
 * 
 * SI EL NÚMERO INTRODUCIDO ES MENOR
 * QUE EL QUE TIENE QUE ADIVINAR, LE DA EL MENSAJE
 * DE "BUSCO NUMERO MAYOR"
 * 
 * SI EL NÚMERO INTRODUCIDO ES MAYOR
 * QUE EL QUE TIENE QUE ADIVINAR, LE DA EL MENSAJE
 * DE "BUSCO NUMERO MENOR"
 * 
 * SI EL USUARIO ACIERTA, LE DAMOS UN MENSAJE
 * DE ENHORABUENA
 * 
 * Y SI SE QUEDAN SIN INTENTOS, LE DECIMOS
 * "GAME OVER" Y LE DAMOS LA SOLUCIÓN DEL NÚMERO
 * BUSCADO
 */

public class AdivinaNumero {

}
